# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-28 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='media/blogresimleri/blog.jpg', upload_to='media/blogresimleri/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, help_text='Bu alani bos birakabilirsiniz.', max_length=255, null=True),
        ),
    ]
