# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-21 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180228_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(help_text='Link, otomatik alinir. Degistirmeyiniz!', max_length=80, null=True),
        ),
    ]
