# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-21 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, upload_to='blogvideolari/%Y/%m/%d'),
        ),
    ]
